name: Build-Windows

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'script/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'script/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore src/escape-from-wizard.csproj

      - name: Restore tools
        run: dotnet tool restore
        working-directory: src

      - run: dotnet build src/escape-from-wizard.csproj --configuration Release --no-restore

      - name: Build content
        run: dotnet mgcb /@:"Game/Content/Content.mgcb" /platform:Windows
        working-directory: src

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            src/bin/Release/
            src/bin/Windows/
      - run: |
          mkdir package
          cp -r src/bin/Release/* package/
          cp -r src/bin/Windows/* package/ || true
          powershell Compress-Archive -Path src/bin/Release/*,src/bin/Windows/* -DestinationPath EscapeFromWizard_Windows_Release.zip
      - uses: softprops/action-gh-release@v2
        with:
          name: Latest Windows Build
          tag_name: latest-windows
          files: EscapeFromWizard_Windows_Release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
