name: Build-Linux

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'script/**'
      - '.github/workflows/build-linux.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'script/**'
      - '.github/workflows/build-linux.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/escape-from-wizard.csproj

      - name: Restore tools
        run: dotnet tool restore
        working-directory: src

      - name: Build content
        run: dotnet mgcb /@:"Game/Content/Content.mgcb" /platform:DesktopGL
        working-directory: src

      - name: Publish
        run: dotnet publish src/escape-from-wizard.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Copy native dependencies
        run: |
          cp src/bin/Debug/net8.0/runtimes/linux-x64/native/libSDL2-2.0.so src/bin/Release/net8.0/linux-x64/publish/ || true
          cp src/bin/Debug/net8.0/runtimes/linux-x64/native/libopenal.so.1 src/bin/Release/net8.0/linux-x64/publish/ || true

      - name: Copy Content
        run: |
          mkdir -p src/bin/Release/net8.0/linux-x64/publish/Content
          cp -r src/bin/Content/DesktopGL/Resource src/bin/Release/net8.0/linux-x64/publish/Content/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-publish
          path: src/bin/Release/net8.0/linux-x64/publish/

      - name: Zip build output
        run: |
          cd src/bin/Release/net8.0/linux-x64/publish
          zip -r ../../../EscapeFromWizard_Linux_Release.zip .

      - uses: softprops/action-gh-release@v2
        with:
          name: Latest Linux Build
          tag_name: latest-linux
          files: src/bin/Release/EscapeFromWizard_Linux_Release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
